src/Invoice/Entity/Invoice.php
<?php

namespace App\Invoice\Entity;

use Doctrine\ORM\Mapping as ORM;
use Money\Money;

/**
 * @ORM\Entity()
 * @ORM\Table(name="invoices")
 *
 * @final
 */
class Invoice
{
    private const EARLY_INVOICE_UPLOAD_PERIOD_IN_DAYS = 30;
    private const EARLY_INVOICE_UPLOAD_SELL_PRICE_COEFFICIENT = '0.5';
    private const LATE_INVOICE_UPLOAD_SELL_PRICE_COEFFICIENT = '0.3';

    /**
     * @ORM\Id
     * @ORM\Column(type="string", unique=true)
     */
    private string $id;

    /**
     * @ORM\Column(type="money")
     */
    private Money $amount;

    /**
     * @ORM\Column(type="date_immutable")
     */
    private \DateTimeImmutable $uploadedOn;

    /**
     * @ORM\Column(type="date_immutable")
     */
    private \DateTimeImmutable $dueOn;

    public function __construct(string $id, Money $amount, \DateTimeImmutable $uploadedOn, \DateTimeImmutable $dueOn)
    {
        self::assertAmountMustNotBeNegative($amount);

        $this->id = $id;
        $this->amount = $amount;
        $this->uploadedOn = $uploadedOn;
        $this->dueOn = $dueOn;
    }

    public function getId(): string
    {
        return $this->id;
    }

    public function getAmount(): Money
    {
        return $this->amount;
    }

    public function getUploadedOn(): \DateTimeImmutable
    {
        return $this->uploadedOn;
    }

    public function getDueOn(): \DateTimeImmutable
    {
        return $this->dueOn;
    }

    public function getSellPrice(): Money
    {
        if ($this->getDaysBetweenUploadedDateAndDueDate() > self::EARLY_INVOICE_UPLOAD_PERIOD_IN_DAYS) {
            return $this->getAmount()->multiply(self::EARLY_INVOICE_UPLOAD_SELL_PRICE_COEFFICIENT);
        }

        return $this->getAmount()->multiply(self::LATE_INVOICE_UPLOAD_SELL_PRICE_COEFFICIENT);
    }

    private function getDaysBetweenUploadedDateAndDueDate(): int
    {
        if ($this->getUploadedOn() >= $this->getDueOn()) {
            return 0;
        }

        return $this->getUploadedOn()->diff($this->getDueOn())->days ?: 0;
    }

    private static function assertAmountMustNotBeNegative(Money $amount): void
    {
        if ($amount->isNegative()) {
            throw new \LogicException('Amount must not be negative.');
        }
    }
}

src/Invoice/Form/UploadInvoicesSheetFormType.php
<?php

namespace App\Invoice\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Validator\Constraints as Assert;

final class UploadInvoicesSheetFormType extends AbstractType
{
    /**
     * @inheritDoc
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        parent::buildForm($builder, $options);

        $builder
            ->add('invoicesSheetFile', FileType::class, [
                'label' => 'Import CSV file',
                'required' => true,
                'constraints' => [
                    new Assert\NotBlank(),
                    new Assert\File([
                        'mimeTypes' => ['text/plain', 'text/csv', 'application/csv'],
                        'mimeTypesMessage' => 'Please upload a valid CSV file',
                    ]),
                ],
            ])
        ;
    }
}

src/Controller/InvoiceController.php
<?php

namespace App\Controller;

use App\Invoice\Form\UploadInvoicesSheetFormType;
use App\Invoice\Import\InvoicesSheetImporter;
use App\Invoice\Import\Report\InvoicesImportLoggerInterface;
use App\Invoice\Import\SheetParser\CSVInvoicesSheetFileParser;
use App\Invoice\Repository\InvoiceRepositoryInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

final class InvoiceController extends AbstractController
{
    private InvoicesSheetImporter $invoicesImporter;
    private InvoiceRepositoryInterface $invoiceRepository;
    private CSVInvoicesSheetFileParser $csvInvoicesSheetFileParser;
    private InvoicesImportLoggerInterface $invoicesImportLogger;

    public function __construct(
        InvoicesSheetImporter $invoicesImporter,
        InvoiceRepositoryInterface $invoiceRepository,
        CSVInvoicesSheetFileParser $csvInvoicesSheetFileParser,
        InvoicesImportLoggerInterface $invoicesImportLogger
    ){
        $this->invoicesImporter = $invoicesImporter;
        $this->invoiceRepository = $invoiceRepository;
        $this->csvInvoicesSheetFileParser = $csvInvoicesSheetFileParser;
        $this->invoicesImportLogger = $invoicesImportLogger;
    }

    /**
     * @Route("/", name="invoices")
     */
    public function list(): Response
    {
        $uploadInvoicesSheetForm = $this->createForm(UploadInvoicesSheetFormType::class, [], [
            'action' => $this->generateUrl('invoices_import'),
        ]);

        return $this->render('invoice/list.html.twig', [
            'uploadInvoicesSheetForm' => $uploadInvoicesSheetForm->createView(),
            'invoices' => $this->invoiceRepository->findAll(), // @todo pagination required
        ]);
    }

    /**
     * @Route("/import", name="invoices_import")
     */
    public function importSheet(Request $request): Response
    {
        $importReport = null;

        $uploadInvoicesSheetForm = $this->createForm(UploadInvoicesSheetFormType::class);
        $uploadInvoicesSheetForm->handleRequest($request);

        if ($uploadInvoicesSheetForm->isSubmitted() && $uploadInvoicesSheetForm->isValid()) {
            $invoicesSheetFile = $uploadInvoicesSheetForm->getData()['invoicesSheetFile'];

            $this->invoicesImporter->importSheet($invoicesSheetFile, $this->csvInvoicesSheetFileParser);

            $importReport = $this->invoicesImportLogger->getFreshReport($invoicesSheetFile);
        }

        return $this->render('invoice/import_report.html.twig', [
            'uploadInvoicesSheetForm' => $uploadInvoicesSheetForm->createView(),
            'importReport' => $importReport,
        ]);
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        {% block stylesheets %}{% endblock %}
    </head>
    <body>
        {% block body %}{% endblock %}
        {% block javascripts %}{% endblock %}
    </body>
</html>

templates/invoice/import_report.html.twig
{% extends 'base.html.twig' %}

{% set title = 'Import report' %}

{% block title %}
    {{ title }}
{% endblock %}

{% block body %}
    <h1>{{ title }}</h1>

    <a href="{{ path('invoices') }}">Back</a>

    <div>
        {% include 'invoice/include/upload_invoices_sheet_form.html.twig' with { uploadInvoicesSheetForm: uploadInvoicesSheetForm } only %}
    </div>

    <hr/>

    {% if importReport is not empty %}
        <p>Added: {{ importReport.numberOfSuccessfulImportedInvoices }}</p>
        <p>Errors: {{ importReport.failureMessages|length }}</p>

        {% if importReport.failureMessages is not empty %}
            <ul>
                {% for message in importReport.failureMessages %}
                    <li>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}
    {% endif %}
{% endblock %}

templates/invoice/include/upload_invoices_sheet_form.html.twig
{{ form_start(uploadInvoicesSheetForm) }}
    {{ form_widget(uploadInvoicesSheetForm) }}
    <button type="submit">Import</button>
{{ form_end(uploadInvoicesSheetForm) }}

templates/invoice/list.html.twig
{% extends 'base.html.twig' %}

{% set title = 'Invoices' %}

{% block title %}
    {{ title }}
{% endblock %}

{% block body %}
    <h1>{{ title }}</h1>

    <div>
        {% include 'invoice/include/upload_invoices_sheet_form.html.twig' with { uploadInvoicesSheetForm: uploadInvoicesSheetForm } only %}
    </div>

    <hr/>

    {% if invoices is not empty %}
        <table border="1">
            <thead>
                <tr>
                    <th scope="col">Id</th>
                    <th scope="col">Amount</th>
                    <th scope="col">Due on</th>
                    <th scope="col">Uploaded on</th>
                    <th scope="col">Sell price</th>
                </tr>
            </thead>
            <tbody>
                {% set dateFormat = 'm/d/Y' %}

                {% for invoice in invoices %}
                    <tr>
                        <td>{{ invoice.id }}</td>
                        <td>{{ invoice.amount|money }}</td>
                        <td>{{ invoice.dueOn|date(dateFormat) }}</td>
                        <td>{{ invoice.uploadedOn|date(dateFormat) }}</td>
                        <td>{{ invoice.sellPrice|money }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% endif %}
{% endblock %}